### ISSUE TITLE
post some error

### ISSUE THREAD

**Issue by ycdm** [PAC-ROM/pac-rom#26]
## pacman 4.4 rc3 oneplus

setting - applicatin manager  crash ：（

12-05 15:06:51.854  24523-24523/com.android.settings E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.android.settings, PID: 24523
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
            at android.content.res.Resources.loadDrawable(Resources.java:2249)
            at android.content.res.Resources.getDrawable(Resources.java:733)
            at android.content.res.Resources.getDrawable(Resources.java:711)
            at android.content.res.XResources.getDrawable(XResources.java:521)
            at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:666)
            at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:148)
            at android.widget.AppSecurityPermissions$MyPermissionGroupInfo.loadGroupIcon(AppSecurityPermissions.java:107)
            at android.widget.AppSecurityPermissions$PermissionItemView.setPermission(AppSecurityPermissions.java:165)
            at android.widget.AppSecurityPermissions.getPermissionItemView(AppSecurityPermissions.java:527)
            at android.widget.AppSecurityPermissions.getPermissionItemView(AppSecurityPermissions.java:516)
            at android.widget.AppSecurityPermissions.displayPermissions(AppSecurityPermissions.java:495)
            at android.widget.AppSecurityPermissions.getPermissionsView(AppSecurityPermissions.java:472)
            at android.widget.AppSecurityPermissions.getPermissionsViewWithRevokeButtons(AppSecurityPermissions.java:460)
            at com.android.settings.applications.InstalledAppDetails.refreshUi(InstalledAppDetails.java:956)
            at com.android.settings.applications.InstalledAppDetails.onResume(InstalledAppDetails.java:719)
            at android.app.Fragment.performResume(Fragment.java:1743)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:924)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
            at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1863)
            at android.app.Activity.performResume(Activity.java:5447)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2814)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2848)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2288)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
12-05 15:06:54.654  17114-17114/com.android.settings E/ResourceType﹕ Style contains key with bad package: 0x00000000
12-05 15:06:54.654  17114-17114/com.android.settings E/ResourceType﹕ Style contains key with bad package: 0x00000000
12-05 15:06:54.934      844-901/system_process E/PowerManagerService﹕ Invalid boost duration: 0
12-05 15:06:54.934      844-856/system_process E/PowerManagerService﹕ Invalid boost duration: 0
12-05 15:06:55.484  17114-17114/com.android.settings E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
12-05 15:06:55.484  17114-17114/com.android.settings E/ResourcesManager﹕ Unable to get pkg com.eg.android.AlipayGphone
    android.os.TransactionTooLargeException
            at android.os.BinderProxy.transact(Native Method)
            at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:1651)
            at android.app.ResourcesManager.setActivityIcons(ResourcesManager.java:329)
            at android.app.ResourcesManager.getTopLevelResources(ResourcesManager.java:239)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
            at android.app.ResourcesManager.getTopLevelResources(Native Method)
            at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1543)
            at android.app.LoadedApk.getResources(LoadedApk.java:487)
            at android.app.ContextImpl.<init>(ContextImpl.java:2102)
            at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1971)
            at android.app.ContextImpl.createPackageContext(ContextImpl.java:1949)
            at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:643)
            at com.android.settings.accounts.AuthenticatorHelper.getLabelForType(AuthenticatorHelper.java:99)
            at com.android.settings.Settings.insertAccountsHeaders(Settings.java:810)
            at com.android.settings.Settings.updateHeaderList(Settings.java:742)
            at com.android.settings.Settings.onBuildHeaders(Settings.java:681)
            at android.preference.PreferenceActivity$1.handleMessage(PreferenceActivity.java:242)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Nick0703** [comment]
Jira! ：（

**Comment by Nick0703** [comment]
You're using xposed framework! We don't support xposed framework...

**Comment by Nick0703** [comment]
Btw this is an xposed framework issue, report that to the xposed framework dev.
